name: Build Windows Flutter App

on:
  push:
    branches:
      - main  # 或其他触发条件

jobs:
  # 设置 Flutter 环境
  build-windows-app:
    runs-on: windows-latest
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
      # 缓存 Flutter SDK
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\.flutter\bin\flutter
          key: ${{ runner.os }}-flutter
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-
      # 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
      # 获取依赖
      - name: Install dependencies
        run: flutter pub get
      # 运行测试
      - name: Run tests
        run: flutter test
      # 编译 .app
      - name: Build Windows App (release)
        run: flutter build windows --release
      # 上传 APK 为工件
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-app
          path: build/windows/runner/Release/*.exe
