name: Build Windows Flutter App

on:
  push:
    branches:
      - main  # 或其他触发条件

jobs:
  # 设置 Flutter 环境
  build-windows-app:
    runs-on: windows-latest
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
      # 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
      # 获取依赖
      - name: Install dependencies
        run: flutter pub get
      # 运行测试
      - name: Run tests
        run: flutter test
      # 编译 exe
      - name: Build Windows App (release)
        run: flutter build windows --release
      # 打包 exe 和 dll
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: yibubang-windows-release.zip
          directory: build/windows/runner/Release
      # 上传打包后的 zip 为工件
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yibubang-windows-release
          path: build/windows/runner/Release/yibubang-windows-release.zip
